author:
  name: Lars Millberg
  email: lars.millberg@gmail.com
title: Pictures and Workshops
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: >-
  Experience 3 days of focussed learning and take your photography to a new
  level
color:
  saturation: 0.3021688442677259
  brandStrength: 0.822326845722273
  lightness: 0.5626328957732767
  brandColors:
    - '#FFF1D7'
    - '#000000'
    - '#CABCCA'
    - '#005685'
    - '#634F5A'
  rhythmicContrast: 0.001164625165984035
typography_spectrum: 0.04707661084830761
layout_spectrum: 0.7975295
name: EastWestTogs
