typography_spectrum: 0.04707661084830761
color:
  brandStrength: 0.822326845722273
  lightness: 0.5626328957732767
  saturation: 0.30216884426772594
  rhythmicContrast: 0.0011646251659840345
  brandColors:
    - '#10222B'
    - '#95AB63'
    - '#BDD684'
    - '#E2F0D6'
    - '#F6FFE0'
layout_spectrum: 0.3255661614239216
author:
  name: Lars Millberg
  email: lars.millberg@gmail.com
name: EastWestTogs
title: Pictures and Workshops
description: Experience 3 days of focussed learning to take your photography to a new level
